### ISSUE TITLE
Acc gen

### ISSUE THREAD

**Issue by 123345666777777777777777777777777** [YaBoyMH/Blooket-Hack-Request#5]
Wut is Ee.cc mail?

**Comment by YaBoyMH** [comment]
It is the email that it automatically generates for each account.

**Comment by YaBoyMH** [comment]
All I can do is get the most recent version of the script and replace it. But to be honest it just doesn't work half of the time, I don't know why and I don't know how to fix it. What you have to do to make it work is you have to be on the sign up screen, click the bookmark it will ask you how many logins to generate then you put in the information and then you have to logins, hope that helps! 👍
