### ISSUE TITLE
Acc Gen isn't working

### ISSUE THREAD

**Issue by idkbrolool** [YaBoyMH/Blooket-Hack-Request#6]
Could you please fix this, and if you would, I would really appreciate it.

**Comment by sieognajkwe69** [comment]
ill try but it isnt my script

**Comment by YaBoyMH** [comment]
Ill fix it if you follow.

**Comment by YaBoyMH** [comment]
I'm just joking, all I can do is get the most recent version of the script and replace it. But to be honest it just doesn't work half of the time, I don't know why and I don't know how to fix it. What you have to do to make it work is you have to be on the sign up screen, click the bookmark it will ask you how many logins to generate then you put in the information and then you have to logins, hope that helps! 👍

**Comment by idkbrolool** [comment]
thx!

**Comment by YaBoyMH** [comment]
your welcome!
